spring:
  application:
    name: microvolunteer

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/microvolunteer}
    username: ${DB_USERNAME:microvolunteer}
    password: ${DB_PASSWORD:secure_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL:false}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8081}

keycloak:
  realm: ${KEYCLOAK_REALM:microvolunteer}
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

app:
  jwt:
    secret: ${JWT_SECRET:microvolunteer-secret-key-that-should-be-at-least-256-bits-long-for-security}
    expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - url: /v3/api-docs
        name: Microvolunteer API

logging:
  level:
    com.microvolunteer: ${LOG_LEVEL:INFO}
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: ${LOG_FILE:logs/microvolunteer.log}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:when-authorized}
