spring:
  application:
    name: micro-volunteering
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:micro_volunteering}?useUnicode=true&characterEncoding=UTF-8&stringtype=unspecified&ApplicationName=micro-volunteering
    username: ${DB_USERNAME:micro_volunteering}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-init-sql: SET client_encoding = 'UTF8'
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          provider_disables_autocommit: false
        hbm2ddl:
          charset_name: UTF-8

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:docker-secret-key-for-coursework-only-do-not-use-in-production-123456789}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.example: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized