spring:
  application:
    name: microvolunteer

  datasource:
    url: jdbc:postgresql://localhost:5433/microvolunteer_dev
    username: ${DB_USERNAME:microvolunteer}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8081

# Keycloak конфігурація
keycloak:
  realm: microvolunteer
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

# JWT конфігурація
app:
  jwt:
    secret: ${JWT_SECRET:microvolunteer-secret-key-that-should-be-at-least-256-bits-long-for-security}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours

  # File upload
  upload:
    dir: ${UPLOAD_DIR:uploads}

# Swagger конфігурація
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

# Логування
logging:
  level:
    com.microvolunteer: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized