spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/microvolunteer_dev
    username: microvolunteer
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Keycloak конфігурація для розробки
keycloak:
  realm: microvolunteer
  auth-server-url: http://localhost:8082
  admin:
    username: admin
    password: admin

# JWT конфігурація для розробки
app:
  jwt:
    secret: microvolunteer-dev-secret-key-that-should-be-at-least-256-bits-long-for-development
    expiration: 86400000 # 24 hours

  # File upload для розробки
  upload:
    dir: uploads

# Логування для розробки
logging:
  level:
    com.microvolunteer: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management endpoints для розробки
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
