spring:
  application:
    name: microvolunteer-dev

  # H2 база данных для разработки
  datasource:
    url: jdbc:h2:mem:microvolunteer_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: ${SHOW_SQL:true}

  # Flyway отключен для dev профиля, используем DDL auto
  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8081}

# Keycloak конфигурация для разработки (mock)
keycloak:
  realm: microvolunteer-dev
  auth-server-url: http://localhost:8080
  admin:
    username: admin
    password: admin

# JWT конфигурация для разработки
app:
  jwt:
    secret: microvolunteer-dev-secret-key-for-testing-purposes-only-not-for-production
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours

# Swagger конфигурация для разработки
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    urls:
      - url: /v3/api-docs
        name: Microvolunteer API v1.0

# Логирование для разработки
logging:
  level:
    com.microvolunteer: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/microvolunteer-dev.log}

# Management endpoints для разработки
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,mappings
  endpoint:
    health:
      show-details: always
